Create zh_CN.lang
TheCyberBrick/The-Betweenlands pull request #378
Opened 2017-03-18 06:59 UTC by DLslime

update 1.10.2

2017-03-20 19:09 UTC, TheCyberBrick commented
Hey, thanks for updating it! I'll check it out soon

2017-03-31 18:05 UTC, TartaricAcid requested changes
Thanks for your translation, but some entries need to be correct.

2017-03-31 18:05 UTC, TartaricAcid commented on src/main/resources/assets/thebetweenlands/lang/zh_CN.lang
> +command.blevent.usage.toggle=/blevent 切换，激活 <事件名称>
Do not translate the `toggle`

2017-03-31 18:05 UTC, TartaricAcid commented on src/main/resources/assets/thebetweenlands/lang/zh_CN.lang
> +#item.thebetweenlands.record.ancient.desc=Voog2 - Ancient
Delete all Chinese in there entries.

2017-04-01 11:42 UTC, DLslime commented on src/main/resources/assets/thebetweenlands/lang/zh_CN.lang
> +command.blevent.usage.toggle=/blevent 切换，激活 <事件名称>
Thanks for reminding me.

2017-04-01 12:47 UTC, TartaricAcid approved these changes

2018-05-29 12:33 UTC, closed without merging